// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: core/v1/core.proto

package corev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/HJH0924/agent-sandbox/sdk/go/core/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CoreServiceName is the fully-qualified name of the CoreService service.
	CoreServiceName = "core.v1.CoreService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CoreServiceInitSandboxProcedure is the fully-qualified name of the CoreService's InitSandbox RPC.
	CoreServiceInitSandboxProcedure = "/core.v1.CoreService/InitSandbox"
)

// CoreServiceClient is a client for the core.v1.CoreService service.
type CoreServiceClient interface {
	InitSandbox(context.Context, *connect.Request[v1.InitSandboxRequest]) (*connect.Response[v1.InitSandboxResponse], error)
}

// NewCoreServiceClient constructs a client for the core.v1.CoreService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCoreServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CoreServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	coreServiceMethods := v1.File_core_v1_core_proto.Services().ByName("CoreService").Methods()
	return &coreServiceClient{
		initSandbox: connect.NewClient[v1.InitSandboxRequest, v1.InitSandboxResponse](
			httpClient,
			baseURL+CoreServiceInitSandboxProcedure,
			connect.WithSchema(coreServiceMethods.ByName("InitSandbox")),
			connect.WithClientOptions(opts...),
		),
	}
}

// coreServiceClient implements CoreServiceClient.
type coreServiceClient struct {
	initSandbox *connect.Client[v1.InitSandboxRequest, v1.InitSandboxResponse]
}

// InitSandbox calls core.v1.CoreService.InitSandbox.
func (c *coreServiceClient) InitSandbox(ctx context.Context, req *connect.Request[v1.InitSandboxRequest]) (*connect.Response[v1.InitSandboxResponse], error) {
	return c.initSandbox.CallUnary(ctx, req)
}

// CoreServiceHandler is an implementation of the core.v1.CoreService service.
type CoreServiceHandler interface {
	InitSandbox(context.Context, *connect.Request[v1.InitSandboxRequest]) (*connect.Response[v1.InitSandboxResponse], error)
}

// NewCoreServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCoreServiceHandler(svc CoreServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	coreServiceMethods := v1.File_core_v1_core_proto.Services().ByName("CoreService").Methods()
	coreServiceInitSandboxHandler := connect.NewUnaryHandler(
		CoreServiceInitSandboxProcedure,
		svc.InitSandbox,
		connect.WithSchema(coreServiceMethods.ByName("InitSandbox")),
		connect.WithHandlerOptions(opts...),
	)
	return "/core.v1.CoreService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CoreServiceInitSandboxProcedure:
			coreServiceInitSandboxHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCoreServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCoreServiceHandler struct{}

func (UnimplementedCoreServiceHandler) InitSandbox(context.Context, *connect.Request[v1.InitSandboxRequest]) (*connect.Response[v1.InitSandboxResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("core.v1.CoreService.InitSandbox is not implemented"))
}
