version: "2"
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - lll
    - staticcheck
    - unused
  settings:
    errcheck:
      disable-default-exclusions: true
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - io/ioutil.ReadFile
        - io.Copy(*bytes.Buffer)
        - io.Copy(os.Stdout)
    lll:
      line-length: 120
      tab-width: 1
    staticcheck:
      checks:
        - all
        - -ST*
        - -QF*
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - lll
        source: (// .*https?://.*$)|(`gorm:".*"`)
      - linters:
          - lll
        path: .*/model/.*\.go$
      - linters:
          - dupl
          - errcheck
          - gocyclo
          - gosec
          - lll
        path: _test\.go
    paths:
      - sdk-ext/
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - localmodule
        - default
      custom-order: true
    gofumpt:
      module-path: github.com/HJH0924/agent-sandbox
      extra-rules: false
  exclusions:
    generated: lax
    paths:
      - sdk-ext/
      - third_party$
      - builtin$
      - examples$
