services:
  agent-sandbox:
    build:
      context: .
      dockerfile: e2b.Dockerfile
    command: /app/bin/api-server -c /app/configs/config.yaml
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
