name: Format Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    name: Check Code Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Install formatting tools
        run: |
          go install mvdan.cc/gofumpt@latest
          go install github.com/incu6us/goimports-reviser/v3@latest

      - name: Check format with gofumpt
        run: |
          if [ -n "$(gofumpt -l .)" ]; then
            echo "The following files need formatting:"
            gofumpt -l .
            echo ""
            echo "Please run 'make format' to fix formatting issues"
            exit 1
          fi

      - name: Check imports with goimports-reviser
        run: |
          goimports-reviser -imports-order=std,project,company,general -list-diff -recursive ./
