name: Lint Check

on:
  workflow_run:
    workflows: ["Format Check"]
    types:
      - completed
    branches:
      - main

jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: -c .golangci.yml ./...
